# Generated by Django 2.2.7 on 2020-05-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BangladeshData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalCases', models.IntegerField()),
                ('casesToday', models.IntegerField()),
                ('totalDeaths', models.IntegerField()),
                ('deathsToday', models.IntegerField()),
                ('totalRecovered', models.IntegerField()),
                ('RecoveredToday', models.IntegerField()),
                ('totalTests', models.IntegerField()),
                ('testsToday', models.IntegerField()),
                ('updatedAt', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DistrictData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districtName', models.CharField(max_length=100, unique=True)),
                ('eName', models.CharField(max_length=100, unique=True)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('totalCases', models.IntegerField()),
                ('casesToday', models.IntegerField()),
                ('casesYesterday', models.IntegerField()),
                ('updatedAt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
